apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespaces.yaml
  - control-plane-ingress.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:ef41bafeca40cc5a54bb1f0a1c3eff4ef96c476dc2e3038baa7d9ffc40494a46
