apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespaces.yaml
  - control-plane-ingress.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:84432db7ef8df0c17dabe1b56deae4972473510160b922b017cb84e9c4c1276b
