apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespaces.yaml
  - control-plane-ingress.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:cd6a9d95acf31b9ddd43c9d2cfd50ee75adc28329de188e2683fbeaac8c41bb2
