apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-external-secrets-bootstrap
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/k8s/staging/external-secrets/bootstrap
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-external-secrets-runtime-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: staging-external-secrets-bootstrap
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/k8s/staging/external-secrets/runtime
  healthChecks:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      name: runtime-secrets
      namespace: runtime-pool
