apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: runtime-secrets
  namespace: runtime-pool
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: runtime-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: agent-failure/staging/runtime-secrets
