apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: runtime-pool
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secretsmanager-credentials
            key: access-key-id
            namespace: runtime-pool
          secretAccessKeySecretRef:
            name: aws-secretsmanager-credentials
            key: secret-access-key
            namespace: runtime-pool
