apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - control-plane-deployment.yaml
  - control-plane-provisioning-worker-deployment.yaml
  - control-plane-evaluator-worker-deployment.yaml
  - control-plane-cleanup-worker-deployment.yaml
  - control-plane-session-objective-completed-worker-deployment.yaml
  - control-plane-session-hint-unlock-worker-deployment.yaml
  - control-plane-session-completed-worker-deployment.yaml
  - control-plane-session-feedback-created-worker-deployment.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:149b2dd11e1c9ad1244c9e6678095c525e2a1c81eb8e941ca47c0c72021ffe78
