apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - control-plane-deployment.yaml
  - control-plane-provisioning-worker-deployment.yaml
  - control-plane-evaluator-worker-deployment.yaml
  - control-plane-cleanup-worker-deployment.yaml
  - control-plane-session-objective-completed-worker-deployment.yaml
  - control-plane-session-hint-unlock-worker-deployment.yaml
  - control-plane-session-completed-worker-deployment.yaml
  - control-plane-session-feedback-created-worker-deployment.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:4ababc9d2698b78fca7de9a03e467c830fbecc6f9df8ddbd2b81a530fc25ff8f
