apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - control-plane-worker-rbac.yaml
  - control-plane-config.yaml
  - control-plane-deployment.yaml
  - control-plane-service.yaml
  - control-plane-provisioning-worker-deployment.yaml
  - control-plane-evaluator-worker-deployment.yaml
  - control-plane-cleanup-worker-deployment.yaml
  - control-plane-session-objective-completed-worker-deployment.yaml
  - control-plane-session-hint-unlock-worker-deployment.yaml
  - control-plane-session-completed-worker-deployment.yaml
  - control-plane-session-feedback-created-worker-deployment.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:d25e252e1695fa11ab1d365c9dcbeda30d36aed2ffac8127f8ee9d3f26aa2d32
