apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets/flux-kustomizations.yaml
  - ../base
  - namespaces.yaml
  - control-plane-ingress.yaml
  - clusterissuer-letsencrypt-prod.yaml
patches:
  - path: control-plane-config-patch.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:aba38074d11091d8fffc14c87bd6f8c3aa0f876a19b3299d651cdc613cdcac39
