apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets/namespace.yaml
  - external-secrets/helm-repository.yaml
  - external-secrets/helm-release.yaml
  - external-secrets/secret-store.yaml
  - external-secrets/runtime-secrets-external-secret.yaml
  - ../base
  - namespaces.yaml
  - control-plane-ingress.yaml
  - clusterissuer-letsencrypt-prod.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:4ef8030dc54358da72ba9496defeb14321f1284f24ade1ea5029e9db5d24307f
