apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets/flux-kustomizations.yaml
  - ../base
  - namespaces.yaml
  - control-plane-ingress.yaml
  - clusterissuer-letsencrypt-prod.yaml

images:
  - name: ghcr.io/kwal0203/agent-failure-control-plane
    digest: sha256:b3c7c8a848f7ca242a0c7db7a93c0e1184755850684b9a844dc1b78d22125398
