"""add labs and lab_versions tables

Revision ID: 029317f25cc3
Revises: f9bf06f247c4
Create Date: 2026-04-17 18:11:24.817604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "029317f25cc3"
down_revision: Union[str, Sequence[str], None] = "f9bf06f247c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "labs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name="ck_labs_name_not_empty"),
        sa.CheckConstraint("slug <> ''", name="ck_labs_slug_not_empty"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_labs_slug"),
    )
    op.create_index(op.f("ix_labs_slug"), "labs", ["slug"], unique=False)
    op.create_table(
        "lab_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lab_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version <> ''", name="ck_lab_versions_version_not_empty"),
        sa.ForeignKeyConstraint(["lab_id"], ["labs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lab_id", "version", name="uq_lab_versions_lab_id_version"),
    )
    op.create_index(
        op.f("ix_lab_versions_lab_id"), "lab_versions", ["lab_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lab_versions_lab_id"), table_name="lab_versions")
    op.drop_table("lab_versions")
    op.drop_index(op.f("ix_labs_slug"), table_name="labs")
    op.drop_table("labs")
    # ### end Alembic commands ###
