"""Add learner_explanations table

Revision ID: 31ea27c74892
Revises: 3819d2fc22d8
Create Date: 2026-04-09 19:47:13.189545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31ea27c74892"
down_revision: Union[str, Sequence[str], None] = "3819d2fc22d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learner_explanations",
        sa.Column("explanation_id", sa.UUID(), nullable=False),
        sa.Column("explanation", sa.String(length=2048), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("lab_id", sa.UUID(), nullable=False),
        sa.Column("lab_version_id", sa.UUID(), nullable=False),
        sa.Column(
            "lab_difficulty",
            sa.String(length=32),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "source", sa.String(length=64), server_default="learner", nullable=False
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lab_difficulty IN ('easy', 'medium')",
            name="ck_learner_explanations_lab_difficulty",
        ),
        sa.CheckConstraint(
            "source IN ('learner')", name="ck_learner_explanations_source"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("explanation_id"),
        sa.UniqueConstraint(
            "session_id", "idempotency_key", name="uq_learner_explanations_idempo"
        ),
    )
    op.create_index(
        op.f("ix_learner_explanations_idempotency_key"),
        "learner_explanations",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learner_explanations_session_id"),
        "learner_explanations",
        ["session_id"],
        unique=False,
    )
    op.add_column(
        "trace_events", sa.Column("lab_difficulty", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trace_events", "lab_difficulty")
    op.drop_index(
        op.f("ix_learner_explanations_session_id"), table_name="learner_explanations"
    )
    op.drop_index(
        op.f("ix_learner_explanations_idempotency_key"),
        table_name="learner_explanations",
    )
    op.drop_table("learner_explanations")
    # ### end Alembic commands ###
