"""add trace_events table for event tracing

Revision ID: 7732ce45a984
Revises: 6f1cdf1d1bb0
Create Date: 2026-03-25 14:40:44.758231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7732ce45a984"
down_revision: Union[str, Sequence[str], None] = "6f1cdf1d1bb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trace_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("event_index", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_version", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("lab_id", sa.UUID(), nullable=True),
        sa.Column("lab_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "family IN ('lifecycle', 'learner', 'runtime', 'tool', 'model')",
            name="ck_trace_family",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint(
            "session_id", "event_index", name="uq_trace_session_event_index"
        ),
    )
    op.create_index(
        op.f("ix_trace_events_family"), "trace_events", ["family"], unique=False
    )
    op.create_index(
        op.f("ix_trace_events_occurred_at"),
        "trace_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trace_events_session_id"), "trace_events", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trace_events_session_id"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_occurred_at"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_family"), table_name="trace_events")
    op.drop_table("trace_events")
    # ### end Alembic commands ###
