"""add runtime_id to sessions

Revision ID: 8c00b94f5c9f
Revises: d5e238bc5d10
Create Date: 2026-03-19 22:26:39.894275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c00b94f5c9f"
down_revision: Union[str, Sequence[str], None] = "d5e238bc5d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("runtime_id", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "runtime_id")
    # ### end Alembic commands ###
