"""Add lab_difficulty field to sessions table

Revision ID: bc2b4373c65d
Revises: a53e1ccf3fc2
Create Date: 2026-04-07 13:22:21.696597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc2b4373c65d"
down_revision: Union[str, Sequence[str], None] = "a53e1ccf3fc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("lab_difficulty", sa.String(length=32), nullable=True)
    )
    # 2) Backfill existing rows
    op.execute(
        "UPDATE sessions SET lab_difficulty = 'medium' WHERE lab_difficulty IS NULL"
    )

    # 3) Enforce NOT NULL
    op.alter_column("sessions", "lab_difficulty", nullable=False)

    # 4) Add constraint
    op.create_check_constraint(
        "ck_sessions_lab_difficulty",
        "sessions",
        "lab_difficulty IN ('easy','medium')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_sessions_lab_difficulty", "sessions", type_="check")
    op.drop_column("sessions", "lab_difficulty")
    # ### end Alembic commands ###
