"""Added lab_objectives table

Revision ID: f9bf06f247c4
Revises: 69b7df589e76
Create Date: 2026-04-17 17:54:44.327501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9bf06f247c4"
down_revision: Union[str, Sequence[str], None] = "69b7df589e76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lab_version_id", sa.UUID(), nullable=False),
        sa.Column("objective_key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("label <> ''", name="ck_lab_objectives_label_not_empty"),
        sa.CheckConstraint(
            "objective_key <> ''", name="ck_lab_objectives_objective_key_not_empty"
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name="ck_lab_objectives_sort_order_nonnegative"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lab_version_id", "objective_key", name="uq_lab_objectives_objective_key"
        ),
        sa.UniqueConstraint(
            "lab_version_id", "sort_order", name="uq_lab_objectives_sort_order"
        ),
    )
    op.create_index(
        op.f("ix_lab_objectives_lab_version_id"),
        "lab_objectives",
        ["lab_version_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lab_objectives_lab_version_id"), table_name="lab_objectives")
    op.drop_table("lab_objectives")
    # ### end Alembic commands ###
