"""add idempotency_records table

Revision ID: faa5264afd76
Revises: 262fcc2fbf0d
Create Date: 2026-03-10 13:42:04.267293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "faa5264afd76"
down_revision: Union[str, Sequence[str], None] = "262fcc2fbf0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("last_transition_actor", sa.String(length=32), nullable=False),
        sa.Column("last_transition_reason", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_state"), "sessions", ["state"], unique=False)
    op.create_table(
        "session_transition_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prev_state", sa.String(length=32), nullable=False),
        sa.Column("next_state", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "next_state IN ('CREATED','PROVISIONING','ACTIVE','IDLE','COMPLETED','FAILED','EXPIRED','CANCELLED')",
            name="ck_next_state",
        ),
        sa.CheckConstraint(
            "prev_state IN ('CREATED','PROVISIONING','ACTIVE','IDLE','COMPLETED','FAILED','EXPIRED','CANCELLED')",
            name="ck_prev_state",
        ),
        sa.CheckConstraint(
            "trigger in ('ADMIN_CANCELLED', 'LAUNCH_SUCCEEDED', 'LAUNCH_FAILED', 'PROVISIONING_SUCCEEDED', 'PROVISIONING_FAILED', 'PROVISIONING_MAX_TIME', 'IDLE_MAX_TIME', 'SESSION_MAX_TIME', 'RECONNECT', 'LAB_COMPLETED', 'LAB_FAILED', 'RUNTIME_FAILED')",
            name="ck_trigger",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "idempotency_key", name="uq_transition_session_idempo"
        ),
    )
    op.create_index(
        op.f("ix_session_transition_events_idempotency_key"),
        "session_transition_events",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_transition_events_session_id"),
        "session_transition_events",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("transition_id", sa.UUID(), nullable=True),
        sa.Column(
            "response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["session_transition_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "operation", "idempotency_key", name="uq_idempo_operation_key"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_records_idempotency_key"),
        "idempotency_records",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_operation"),
        "idempotency_records",
        ["operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_session_id"),
        "idempotency_records",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_transition_id"),
        "idempotency_records",
        ["transition_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_idempotency_records_transition_id"), table_name="idempotency_records"
    )
    op.drop_index(
        op.f("ix_idempotency_records_session_id"), table_name="idempotency_records"
    )
    op.drop_index(
        op.f("ix_idempotency_records_operation"), table_name="idempotency_records"
    )
    op.drop_index(
        op.f("ix_idempotency_records_idempotency_key"), table_name="idempotency_records"
    )
    op.drop_table("idempotency_records")
    op.drop_index(
        op.f("ix_session_transition_events_session_id"),
        table_name="session_transition_events",
    )
    op.drop_index(
        op.f("ix_session_transition_events_idempotency_key"),
        table_name="session_transition_events",
    )
    op.drop_table("session_transition_events")
    op.drop_index(op.f("ix_sessions_state"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
