from .types import TraceFamily
from apps.contracts.src.types import (
    TRACE_EVENT_ATTACK_EMAIL_SENT,
    TRACE_EVENT_MALICIOUS_EMAIL_READ,
    TRACE_EVENT_TOKEN_DISCLOSED,
    TRACE_EVENT_TOKEN_DISCLOSURE_ATTEMPTED,
    TRACE_EVENT_TOOL_CALL_FAILED,
    TRACE_EVENT_TOOL_CALL_REQUESTED,
    TRACE_EVENT_TOOL_CALL_SUCCEEDED,
)


LEARNER_VISIBLE_ALLOWLIST: set[tuple[TraceFamily, str]] = {
    ("lifecycle", "SESSION_CREATED"),
    ("learner", "USER_PROMPT_SUBMITTED"),
    ("learner", TRACE_EVENT_ATTACK_EMAIL_SENT),
    ("runtime", "RUNTIME_PROVISION_REQUESTED"),
    ("runtime", "RUNTIME_PROVISION_ACCEPTED"),
    ("runtime", "RUNTIME_PROVISION_FAILED"),
    ("runtime", "TRY_ATTACK_CONSOLE_HINT"),
    ("runtime", TRACE_EVENT_ATTACK_EMAIL_SENT),
    ("runtime", TRACE_EVENT_MALICIOUS_EMAIL_READ),
    ("runtime", TRACE_EVENT_TOKEN_DISCLOSURE_ATTEMPTED),
    ("runtime", TRACE_EVENT_TOKEN_DISCLOSED),
    ("tool", TRACE_EVENT_TOOL_CALL_REQUESTED),
    ("tool", TRACE_EVENT_TOOL_CALL_SUCCEEDED),
    ("tool", TRACE_EVENT_TOOL_CALL_FAILED),
    ("model", "MODEL_TURN_COMPLETED"),
    ("model", "MODEL_TURN_FAILED"),
}
