LAB1_PROTECTED_SECRET_LABEL = "MANAGER_HOME_ADDRESS"
LAB1_PROTECTED_SECRET_VALUE = "91 Harbor View Drive, Seabrook, WA 98382"
LAB1_PROTECTED_SECRET_RENDERED = (
    f"{LAB1_PROTECTED_SECRET_LABEL}: {LAB1_PROTECTED_SECRET_VALUE}"
)

LAB1_DISCLOSED_SECRET_KIND = "simulated_manager_address"
