/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/admin/instructors/provision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Provision Instructor */
    post: operations["provision_instructor_api_v1_admin_instructors_provision_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/enrollment/redeem": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Redeem Enrollment */
    post: operations["redeem_enrollment_api_v1_enrollment_redeem_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/enrollment/validate-class-code": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate Class Code */
    post: operations["validate_class_code_api_v1_enrollment_validate_class_code_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/labs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Labs */
    get: operations["get_labs_api_v1_labs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/labs/{lab_id}/latest-session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Latest Lab Session */
    get: operations["get_latest_lab_session_api_v1_labs__lab_id__latest_session_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pilot-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Pilot Requests */
    get: operations["list_pilot_requests_api_v1_pilot_requests_get"];
    put?: never;
    /** Create Pilot Request */
    post: operations["create_pilot_request_api_v1_pilot_requests_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pilot-requests/{request_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Pilot Request Status */
    patch: operations["update_pilot_request_status_api_v1_pilot_requests__request_id__patch"];
    trace?: never;
  };
  "/api/v1/pilot-requests/{request_id}/approve-and-provision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve And Provision Pilot Request */
    post: operations["approve_and_provision_pilot_request_api_v1_pilot_requests__request_id__approve_and_provision_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pilot-requests/{request_id}/provision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Provision Pilot Request */
    post: operations["provision_pilot_request_api_v1_pilot_requests__request_id__provision_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Sessions */
    get: operations["get_sessions_api_v1_sessions_get"];
    put?: never;
    /** Create Session Endpoint */
    post: operations["create_session_endpoint_api_v1_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Metadata */
    get: operations["get_metadata_api_v1_sessions__session_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/evaluator-feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evaluator Feedback */
    get: operations["evaluator_feedback_api_v1_sessions__session_id__evaluator_feedback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/explanation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Learner Explanation */
    post: operations["learner_explanation_api_v1_sessions__session_id__explanation_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/feedback/mark-seen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Feedback Seen Endpoint */
    post: operations["mark_feedback_seen_endpoint_api_v1_sessions__session_id__feedback_mark_seen_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/hints/mark-seen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Hints Seen Endpoint */
    post: operations["mark_hints_seen_endpoint_api_v1_sessions__session_id__hints_mark_seen_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/inbox/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Inject Session Email */
    post: operations["inject_session_email_api_v1_sessions__session_id__inbox_email_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/report-draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Report Draft */
    get: operations["get_report_draft_api_v1_sessions__session_id__report_draft_get"];
    /** Put Report Draft */
    put: operations["put_report_draft_api_v1_sessions__session_id__report_draft_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/report-evidence": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Report Evidence */
    get: operations["get_report_evidence_api_v1_sessions__session_id__report_evidence_get"];
    /** Put Report Evidence */
    put: operations["put_report_evidence_api_v1_sessions__session_id__report_evidence_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/report/import-selected-evidence": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Import Selected Evidence */
    post: operations["post_import_selected_evidence_api_v1_sessions__session_id__report_import_selected_evidence_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stop Session Endpoint */
    post: operations["stop_session_endpoint_api_v1_sessions__session_id__stop_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{session_id}/trace": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Session Trace */
    get: operations["get_session_trace_api_v1_sessions__session_id__trace_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApiError */
    ApiError: {
      /** Code */
      code: string;
      /** Details */
      details: {
        [key: string]: unknown;
      } | null;
      /** Message */
      message: string;
      /** Retryable */
      retryable: boolean;
    };
    /** ApiErrorEnvelope */
    ApiErrorEnvelope: {
      error: components["schemas"]["ApiError"];
    };
    /** ApproveAndProvisionRequest */
    ApproveAndProvisionRequest: {
      /** Classcode */
      classCode: string;
      /** Classcodemaxuses */
      classCodeMaxUses?: number | null;
      /** Courseid */
      courseId: string;
      /** Coursename */
      courseName: string;
      /**
       * Createinstructorifmissing
       * @default false
       */
      createInstructorIfMissing: boolean;
      /** Instructoremail */
      instructorEmail: string;
    };
    /** ApproveAndProvisionResponse */
    ApproveAndProvisionResponse: {
      /** Approvedstep */
      approvedStep: boolean;
      /** Instructorprovisionerror */
      instructorProvisionError?: string | null;
      instructorProvisionStep?:
        | components["schemas"]["InstructorProvisioningSummaryResponse"]
        | null;
      /** Isretry */
      isRetry: boolean;
      /** Pilotprovisionerror */
      pilotProvisionError?: string | null;
      pilotProvisionStep?:
        | components["schemas"]["ProvisioningSummaryResponse"]
        | null;
      pilotRequest: components["schemas"]["PilotRequestItemResponse"];
      /** Runcorrelationid */
      runCorrelationId: string;
    };
    /** CourseSummary */
    CourseSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
    };
    /** CreatePilotRequest */
    CreatePilotRequest: {
      /** Cohortsize */
      cohortSize?: number | null;
      /** Coursename */
      courseName?: string | null;
      /** Fullname */
      fullName: string;
      /** Notes */
      notes?: string | null;
      /** Role */
      role?: string | null;
      /** University */
      university: string;
      /** Workemail */
      workEmail: string;
    };
    /** CreatePilotRequestResponse */
    CreatePilotRequestResponse: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Requestid */
      requestId: string;
      /** Status */
      status: string;
    };
    /** CreateSessionRequest */
    CreateSessionRequest: {
      /**
       * Lab Id
       * Format: uuid
       */
      lab_id: string;
    };
    /** CreateSessionResponse */
    CreateSessionResponse: {
      session: components["schemas"]["SessionResponse"];
    };
    /** EmailArtifact */
    EmailArtifact: {
      /** Email Body */
      email_body: string;
      /** Email From */
      email_from: string;
      /** Email Id */
      email_id?: string | null;
      /** Email Preview */
      email_preview?: string | null;
      /** Email Subject */
      email_subject: string;
      /** Malicious */
      malicious?: boolean | null;
      /**
       * Source
       * @default learner
       * @constant
       */
      source: "learner";
      /** Urgency Marker */
      urgency_marker?: boolean | null;
    };
    /** EvaluatorFeedbackResponse */
    EvaluatorFeedbackResponse: {
      /** Evidence Snippet */
      evidence_snippet: string;
      /** Reason Code */
      reason_code: string;
      /**
       * Status
       * @enum {string}
       */
      status: "learned" | "progress" | "no_progress" | "session_terminal";
    };
    /** GetFeedbackResponse */
    GetFeedbackResponse: {
      /** Feedback */
      feedback: components["schemas"]["EvaluatorFeedbackResponse"][];
    };
    /** GetLabsResponse */
    GetLabsResponse: {
      /** Labs */
      labs: components["schemas"]["LabCatalogItemResponse"][];
    };
    /** GetSessionMetadataResponse */
    GetSessionMetadataResponse: {
      session: components["schemas"]["SessionMetadataResponse"];
    };
    /** GetSessionReportDraftResponse */
    GetSessionReportDraftResponse: {
      /** Items */
      items: components["schemas"]["ReportEvidenceItem"][];
      sections: components["schemas"]["ReportDraftSections"];
    };
    /** GetSessionReportEvidenceResponse */
    GetSessionReportEvidenceResponse: {
      /** Items */
      items: components["schemas"]["ReportEvidenceItem"][];
    };
    /** GetSessionTraceResponse */
    GetSessionTraceResponse: {
      /** Events */
      events: components["schemas"]["SessionTraceEvent"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** GetSessionsResponse */
    GetSessionsResponse: {
      /** Sessions */
      sessions: components["schemas"]["SessionSummaryResponse"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ImportSelectedEvidenceRequest */
    ImportSelectedEvidenceRequest: {
      /** Event Ids */
      event_ids?: string[] | null;
    };
    /** ImportSelectedEvidenceResponse */
    ImportSelectedEvidenceResponse: {
      /** Items */
      items: components["schemas"]["ReportEvidenceItem"][];
    };
    /** InjectSessionEmailResponse */
    InjectSessionEmailResponse: {
      /**
       * Accepted
       * @default true
       */
      accepted: boolean;
      /** Email Id */
      email_id?: string | null;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
    };
    /** InstructorProvisioningSummaryResponse */
    InstructorProvisioningSummaryResponse: {
      /** Courseid */
      courseId: string;
      /** Coursename */
      courseName: string;
      /** Groupassigned */
      groupAssigned: boolean;
      /** Instructoremail */
      instructorEmail: string;
      /** Instructoruserid */
      instructorUserId?: string | null;
      /** Invitesent */
      inviteSent: boolean;
      /** Membershipcreated */
      membershipCreated: boolean;
      /** Pilotrequestid */
      pilotRequestId: string;
      /**
       * Provisionedat
       * Format: date-time
       */
      provisionedAt: string;
      /** Provisionedby */
      provisionedBy?: string | null;
      /** Provisioningcorrelationid */
      provisioningCorrelationId?: string | null;
      /** Usercreated */
      userCreated: boolean;
    };
    /** LabCapabilitiesResponse */
    LabCapabilitiesResponse: {
      /** Supports Resume */
      supports_resume: boolean;
      /** Supports Uploads */
      supports_uploads: boolean;
    };
    /** LabCatalogItemResponse */
    LabCatalogItemResponse: {
      capabilities: components["schemas"]["LabCapabilitiesResponse"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Summary */
      summary: string;
    };
    /** LatestLabSessionResponse */
    LatestLabSessionResponse: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
    };
    /** LearnerExplanationRequest */
    LearnerExplanationRequest: {
      /** Explanation */
      explanation: string;
    };
    /** LearnerExplanationResponse */
    LearnerExplanationResponse: {
      /**
       * Accepted
       * @default true
       */
      accepted: boolean;
      /**
       * Explanation Id
       * Format: uuid
       */
      explanation_id: string;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
    };
    /** ListPilotRequestsResponse */
    ListPilotRequestsResponse: {
      /** Items */
      items: components["schemas"]["PilotRequestItemResponse"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** MarkSessionFeedbackSeenResponse */
    MarkSessionFeedbackSeenResponse: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Updated Count */
      updated_count: number;
    };
    /** MarkSessionHintsSeenResponse */
    MarkSessionHintsSeenResponse: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Updated Count */
      updated_count: number;
    };
    /** ObjectiveMappingItem */
    ObjectiveMappingItem: {
      /** Label */
      label: string;
      /** Objective Key */
      objective_key: string;
      /** Rubric Target */
      rubric_target: string;
    };
    /** PilotRequestItemResponse */
    PilotRequestItemResponse: {
      /** Cohortsize */
      cohortSize?: number | null;
      /** Coursename */
      courseName?: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Fullname */
      fullName: string;
      /** Notes */
      notes?: string | null;
      /** Requestid */
      requestId: string;
      /** Role */
      role?: string | null;
      /** Sourceip */
      sourceIp?: string | null;
      /** Status */
      status: string;
      /** University */
      university: string;
      /** Workemail */
      workEmail: string;
    };
    /** ProvisionInstructorRequest */
    ProvisionInstructorRequest: {
      /**
       * Createuserifmissing
       * @default false
       */
      createUserIfMissing: boolean;
      /** Instructoremail */
      instructorEmail: string;
      /** Pilotrequestid */
      pilotRequestId: string;
    };
    /** ProvisionInstructorResponse */
    ProvisionInstructorResponse: {
      provisioningSummary: components["schemas"]["InstructorProvisioningSummaryResponse"];
    };
    /** ProvisionPilotRequestPayload */
    ProvisionPilotRequestPayload: {
      /** Classcode */
      classCode: string;
      /** Courseid */
      courseId: string;
      /** Coursename */
      courseName: string;
      /** Instructoremail */
      instructorEmail: string;
      /** Maxuses */
      maxUses?: number | null;
    };
    /** ProvisionPilotRequestResponse */
    ProvisionPilotRequestResponse: {
      /** Created */
      created: boolean;
      provisioningSummary: components["schemas"]["ProvisioningSummaryResponse"];
    };
    /** ProvisioningSummaryResponse */
    ProvisioningSummaryResponse: {
      /** Classcode */
      classCode: string;
      /** Classcodeid */
      classCodeId: string;
      /** Classcodemaxuses */
      classCodeMaxUses?: number | null;
      /** Classcodestatus */
      classCodeStatus: string;
      /** Courseid */
      courseId: string;
      /** Coursename */
      courseName: string;
      /** Instructoremail */
      instructorEmail: string;
      /** Pilotrequestid */
      pilotRequestId: string;
      /**
       * Provisionedat
       * Format: date-time
       */
      provisionedAt: string;
      /** Provisionedby */
      provisionedBy?: string | null;
      /** Provisioningcorrelationid */
      provisioningCorrelationId?: string | null;
    };
    /** PutSessionReportDraftRequest */
    PutSessionReportDraftRequest: {
      /** Items */
      items: components["schemas"]["ReportEvidenceItem"][];
      sections: components["schemas"]["ReportDraftSections"];
    };
    /** PutSessionReportEvidenceRequest */
    PutSessionReportEvidenceRequest: {
      /** Items */
      items: components["schemas"]["ReportEvidenceItem"][];
    };
    /** RedeemEnrollmentRequest */
    RedeemEnrollmentRequest: {
      /** Enrollmenttoken */
      enrollmentToken: string;
    };
    /** RedeemEnrollmentResponse */
    RedeemEnrollmentResponse: {
      course?: components["schemas"]["CourseSummary"] | null;
      /** Enrolled */
      enrolled: boolean;
      /** Error */
      error?: string | null;
    };
    /** ReportDraftSections */
    ReportDraftSections: {
      /**
       * Evidence And Results
       * @default
       */
      evidence_and_results: string;
      /**
       * Executive Summary
       * @default
       */
      executive_summary: string;
      /**
       * Methodology
       * @default
       */
      methodology: string;
      /**
       * Mitigations
       * @default
       */
      mitigations: string;
      /**
       * Threat Model
       * @default
       */
      threat_model: string;
    };
    /** ReportEvidenceItem */
    ReportEvidenceItem: {
      /** Citation Label */
      citation_label?: string | null;
      /**
       * Default Priority
       * @enum {string}
       */
      default_priority: "high" | "medium" | "low";
      /** Description */
      description?: string | null;
      /** Details */
      details?: {
        [key: string]: unknown;
      } | null;
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      /** Event Index */
      event_index: number;
      /** Evidence Strength */
      evidence_strength?: ("high" | "medium" | "low") | null;
      /**
       * Evidence Type
       * @enum {string}
       */
      evidence_type:
        | "exploit_step"
        | "exploit_outcome"
        | "system_context"
        | "coaching_feedback"
        | "noise";
      /**
       * Objective Keys
       * @default []
       */
      objective_keys: string[];
      /** Objective Mapping */
      objective_mapping?:
        | components["schemas"]["ObjectiveMappingItem"][]
        | null;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Position */
      position: number;
      /**
       * Report Section
       * @default unassigned
       */
      report_section: string;
      /** Section Position */
      section_position?: number | null;
      /** Student Note */
      student_note?: string | null;
      /** Title */
      title: string;
      /**
       * Trace Version
       * @default 1
       */
      trace_version: number;
      /** Why It Matters */
      why_it_matters?: string | null;
    };
    /** SessionFeedbackResponse */
    SessionFeedbackResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Feedback Key */
      feedback_key: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Message */
      message: string;
      /** Reason Code */
      reason_code: string;
      /** Seen At */
      seen_at: string | null;
      /**
       * Severity
       * @enum {string}
       */
      severity: "info" | "warning" | "error";
      /** Trigger Event Index */
      trigger_event_index: number | null;
    };
    /** SessionHintResponse */
    SessionHintResponse: {
      /** Hint Key */
      hint_key: string;
      /** Seen At */
      seen_at: string | null;
      /** Sort Order */
      sort_order: number;
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "unlocked";
      /** Text */
      text: string;
      /**
       * Unlock At
       * Format: date-time
       */
      unlock_at: string;
      /** Unlocked At */
      unlocked_at: string | null;
    };
    /** SessionMetadataResponse */
    SessionMetadataResponse: {
      /** Completed At */
      completed_at?: string | null;
      /** Completion Reason Code */
      completion_reason_code?: string | null;
      /**
       * Completion Status
       * @default in_progress
       * @enum {string}
       */
      completion_status:
        | "in_progress"
        | "completed_success"
        | "completed_failure";
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Ended At */
      ended_at: string | null;
      /** Feedback */
      feedback?: components["schemas"]["SessionFeedbackResponse"][];
      /** Feedback Items */
      feedback_items?: components["schemas"]["SessionFeedbackResponse"][];
      /** Hints */
      hints?: components["schemas"]["SessionHintResponse"][];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Interactive */
      interactive: boolean;
      /** Lab Id */
      lab_id: string | null;
      /** Lab Version Id */
      lab_version_id: string | null;
      /** Last Transition Reason */
      last_transition_reason: string | null;
      /** Progress Chips */
      progress_chips?: components["schemas"]["SessionProgressChipResponse"][];
      /** Provisioning Stall Reason Code */
      provisioning_stall_reason_code?: string | null;
      /**
       * Provisioning Stalled
       * @default false
       */
      provisioning_stalled: boolean;
      /** Resume Mode */
      resume_mode: string;
      /** Runtime Files */
      runtime_files?: components["schemas"]["SessionRuntimeFileResponse"][];
      /** Runtime Substate */
      runtime_substate: string | null;
      /** Started At */
      started_at: string | null;
      /** State */
      state: string;
      /**
       * Unread Feedback Count
       * @default 0
       */
      unread_feedback_count: number;
      /**
       * Unread Hint Count
       * @default 0
       */
      unread_hint_count: number;
    };
    /** SessionProgressChipResponse */
    SessionProgressChipResponse: {
      /** Completed At */
      completed_at: string | null;
      /** Label */
      label: string;
      /** Objective Key */
      objective_key: string;
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "complete";
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** SessionResponse */
    SessionResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Lab Id
       * Format: uuid
       */
      lab_id: string;
      /** Lab Version Id */
      lab_version_id: string | null;
      /** Resume Mode */
      resume_mode: string;
      /** State */
      state: string;
    };
    /** SessionRuntimeFileResponse */
    SessionRuntimeFileResponse: {
      /** Content */
      content: string;
      /** Path */
      path: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** SessionSummaryResponse */
    SessionSummaryResponse: {
      /**
       * Completion Status
       * @enum {string}
       */
      completion_status:
        | "in_progress"
        | "completed_success"
        | "completed_failure";
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Lab Id
       * Format: uuid
       */
      lab_id: string;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** State */
      state: string;
    };
    /** SessionTraceEvent */
    SessionTraceEvent: {
      /**
       * Default Priority
       * @default low
       * @enum {string}
       */
      default_priority: "high" | "medium" | "low";
      /** Event Index */
      event_index: number;
      /** Event Type */
      event_type: string;
      /**
       * Evidence Type
       * @default noise
       * @enum {string}
       */
      evidence_type:
        | "exploit_step"
        | "exploit_outcome"
        | "system_context"
        | "coaching_feedback"
        | "noise";
      /**
       * Family
       * @enum {string}
       */
      family: "lifecycle" | "learner" | "runtime" | "tool" | "model";
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Objective Keys */
      objective_keys?: string[];
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /**
       * Report Selectable
       * @default false
       */
      report_selectable: boolean;
      /** Source */
      source: string;
      /** Why It Matters */
      why_it_matters?: string | null;
    };
    /** StopSessionResponse */
    StopSessionResponse: {
      /**
       * Accepted
       * @default true
       */
      accepted: boolean;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** State */
      state: string;
    };
    /** UpdatePilotRequestStatusRequest */
    UpdatePilotRequestStatusRequest: {
      /** Status */
      status: string;
    };
    /** ValidateClassCodeRequest */
    ValidateClassCodeRequest: {
      /** Classcode */
      classCode: string;
      /** Email */
      email: string;
    };
    /** ValidateClassCodeResponse */
    ValidateClassCodeResponse: {
      course?: components["schemas"]["CourseSummary"] | null;
      /** Enrollmenttoken */
      enrollmentToken?: string | null;
      /** Error */
      error?: string | null;
      /** Expiresinseconds */
      expiresInSeconds?: number | null;
      /** Valid */
      valid: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  provision_instructor_api_v1_admin_instructors_provision_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProvisionInstructorRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProvisionInstructorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  redeem_enrollment_api_v1_enrollment_redeem_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RedeemEnrollmentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RedeemEnrollmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  validate_class_code_api_v1_enrollment_validate_class_code_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateClassCodeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidateClassCodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_labs_api_v1_labs_get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetLabsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_latest_lab_session_api_v1_labs__lab_id__latest_session_get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        lab_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LatestLabSessionResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  list_pilot_requests_api_v1_pilot_requests_get: {
    parameters: {
      query?: {
        status?: string | null;
        created_after?: string | null;
        limit?: number;
        offset?: number;
      };
      header: {
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPilotRequestsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_pilot_request_api_v1_pilot_requests_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePilotRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatePilotRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_pilot_request_status_api_v1_pilot_requests__request_id__patch: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePilotRequestStatusRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PilotRequestItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_and_provision_pilot_request_api_v1_pilot_requests__request_id__approve_and_provision_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveAndProvisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApproveAndProvisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  provision_pilot_request_api_v1_pilot_requests__request_id__provision_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProvisionPilotRequestPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProvisionPilotRequestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_sessions_api_v1_sessions_get: {
    parameters: {
      query: {
        lab_id: string;
        limit?: number;
        sort?: string;
      };
      header: {
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  create_session_endpoint_api_v1_sessions_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateSessionResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  get_metadata_api_v1_sessions__session_id__get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionMetadataResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  evaluator_feedback_api_v1_sessions__session_id__evaluator_feedback_get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetFeedbackResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  learner_explanation_api_v1_sessions__session_id__explanation_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LearnerExplanationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LearnerExplanationResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  mark_feedback_seen_endpoint_api_v1_sessions__session_id__feedback_mark_seen_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarkSessionFeedbackSeenResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_hints_seen_endpoint_api_v1_sessions__session_id__hints_mark_seen_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarkSessionHintsSeenResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  inject_session_email_api_v1_sessions__session_id__inbox_email_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailArtifact"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InjectSessionEmailResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  get_report_draft_api_v1_sessions__session_id__report_draft_get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionReportDraftResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  put_report_draft_api_v1_sessions__session_id__report_draft_put: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PutSessionReportDraftRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionReportDraftResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  get_report_evidence_api_v1_sessions__session_id__report_evidence_get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionReportEvidenceResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  put_report_evidence_api_v1_sessions__session_id__report_evidence_put: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PutSessionReportEvidenceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionReportEvidenceResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  post_import_selected_evidence_api_v1_sessions__session_id__report_import_selected_evidence_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json":
          | components["schemas"]["ImportSelectedEvidenceRequest"]
          | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSelectedEvidenceResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  stop_session_endpoint_api_v1_sessions__session_id__stop_post: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StopSessionResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  get_session_trace_api_v1_sessions__session_id__trace_get: {
    parameters: {
      query?: never;
      header: {
        Authorization: string;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetSessionTraceResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorEnvelope"];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
