from apps.contracts.src.lab_identities import AGENT_TOOL_MISUSE

LAB_2_TOOL_MISUSE_ID = AGENT_TOOL_MISUSE.runtime_config_id
AGENT_LAB_2_TOOL_MISUSE_ID = AGENT_TOOL_MISUSE.lab_id
TOOL_MISUSE_AUTHORITY_SIGNER = "Morgan Hale"

TOOL_MISUSE_LAB_IDS = frozenset({LAB_2_TOOL_MISUSE_ID, AGENT_LAB_2_TOOL_MISUSE_ID})
