from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from apps.contracts.src.lab_identities import PRODUCTION_AGENT_LABS  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "apps/frontend/src/labIdentities.generated.ts"


def _typescript_name(slug: str) -> str:
    return slug.replace("-", "_").upper()


def render() -> str:
    lines = [
        "// Generated by scripts/generate_lab_identities.py. Do not edit.",
        "",
    ]
    for identity in PRODUCTION_AGENT_LABS:
        name = _typescript_name(identity.slug)
        lines.extend(
            [
                f'export const {name}_LAB_ID = "{identity.lab_id}";',
                f'export const {name}_LAB_VERSION_ID = "{identity.lab_version_id}";',
                f'export const {name}_RUNTIME_CONFIG_ID = "{identity.runtime_config_id}";',
                f'export const {name}_SLUG = "{identity.slug}";',
                f'export const {name}_VERSION = "{identity.version}";',
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
